### ISSUE TITLE
Update wallet description

### ISSUE THREAD

**Issue by ThierryThevenet** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#131]
Hello, is it possible to update our 2 wallets description.
Thanks
[talao.json](https://github.com/user-attachments/files/18111082/talao.json)
[altme.json](https://github.com/user-attachments/files/18111083/altme.json)

**Comment by cre8** [comment]
Hi @ThierryThevenet ,

yes, just fork the repository, make the changes to your files and open a pull request. Let me know when you need any help.

**Comment by hawkbee1** [comment]
Hello
Here is the pull request @cre8 : https://github.com/openwallet-foundation/digital-wallet-and-agent-overviews-sig/pull/133

**Comment by cre8** [comment]
Got merged, thank you for the update!
