### ISSUE TITLE
organizationalWallet

### ISSUE THREAD

**Issue by samuelmr** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#15]
What's the definition of `organizationalWallet`?

If a wallet can be used both individuals and organizations, what should be the value of `organizationalWallet`?

If a wallet is targeted only to organizations but not to individuals, what should be the value?

**Comment by maaikevanleuken** [comment]
Let's make this not a boolean, but a multiple choice: "natural persons", "organisation", "natural persons + organisations"

**Comment by cre8** [comment]
closing this since we have the difference between cloud and edge.
