### ISSUE TITLE
Additional charcteristics

### ISSUE THREAD

**Issue by samuelmr** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#16]
I suggest adding the following characteristics:
- `holderCapability`: Can hold and present digital credentials
- `issuerCapability`: Can issue digital credentials
- `verifierCapability`: Can verify digital credentials
- `api`: Can be integrated into other systems via an application programming interface
- `webApp`: address of a cloud service agent (e.g. https://www.blockcerts.org/, https://certs.dock.io/, https://connect.trinsic.cloud, https://demo.lissi.id/, https://wallet.essif.sk/, https://wallet.walt.id/) that cannot be downloaded from app stores

**Comment by samuelmr** [comment]
The `download` section doesn´t work well for cloud wallets...

**Comment by maaikevanleuken** [comment]
Let's add all of these.
