### ISSUE TITLE
One or two overviews

### ISSUE THREAD

**Issue by samuelmr** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#2]
This repo will build upon [TNO's Wallet Overview](https://github.com/tno-ssi-lab/wallet-overview) which is scoped to include _holder_ wallets and [Findynet's fork](https://github.com/FindyFi/wallet-overview) which extends the scope to solutions that have _issuer_ and _verifier_ capabilities.

Question: should we maintain two (possibly overlapping) overviews or one, combined overview?

Input from SSI solution vendors is appreciated.

**Comment by samuelmr** [comment]
Pros for maintaining two overviews:
- less clutter for users interested in just wallets (agents with holder capabilities)
- less clutter for users interested in just holistic solutions (issuer/verifier "platforms")

Cons for maintaining two overviews:
- SSI solution vendors need to submit information to two different json files
- duplicate maintenance of the same or very similar functionality (code)
- in some cases, users would need to look for both overviews to find a solution (?)

**Comment by cre8** [comment]
I would suggest to merge them and the user can filter the rows he/she wants to see. He/she is interacting with a web application and not a static list.

We did this approach for the credential comparison group and went fine with it.

**Comment by samuelmr** [comment]
The SIG has decided to merge.

Closing issue.
