### ISSUE TITLE
Renaming columns

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#28]
The new column were limited down and the name from the sig credential comparison group were used.
We should use this issue to discuss renaming.

**Comment by maaikevanleuken** [comment]
Please use the columns as used in the [current overview](https://openwallet-foundation.github.io/digital-wallet-and-agent-overviews-sig/). These columns have discussed extensively. We can always add more columns afterwards.
