### ISSUE TITLE
Adding of the logo

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#29]
To make it easy for the providers, right now you only need to generate one json file that includes a url to the logo.

I would not prefer that people insert a base encoded image since this will blow up the json file!.

We can insert the information that people can add it to the logo folder if they do not want to host it on their own (preferred option)

**Comment by samuelmr** [comment]
By blowing up the JSON, do you mean that data URIs will make the file large and thus slow to load an parse?

Or are you afraid of JSON validity?

**Comment by cre8** [comment]
More the first concern. I see the wallet icon not as important as the included data like names, numbers, bools etc. that can be used for filtering. When we include the logos as base64, it will be responsible of 99% of the file size.

However I understand that it does not look good when we reference to an external hosted images that is not provided anymore.

Suggested solution for the future:
- we are writing a script that will look for external links in the json files, download the content into the repository folder for images and replaces the reference with the link. The same can be done in case someone added a base64 encoded image.

I would not set this open issue to a high priority since the amount of new wallet requests is not high enough. People should have the easiest way to provide information in the short run so we are able to get PRs for the wallets/agents out there,

**Comment by cre8** [comment]
uploading the logo to the repo seems like a good way to go.
