### ISSUE TITLE
Add filters for the rows

### ISSUE THREAD

**Issue by maaikevanleuken** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#38]
Add filters to the overview, to keep it uncluttered.

These filters could be:
- only show wallets
- only show agents
- only show edge (smartphone) wallets
- only show organisational wallets
- show interop profiles

**Comment by cre8** [comment]
So you mean you can hide certain columns to fit the overview better on a smaller screen size without too much scrolling?

**Comment by maaikevanleuken** [comment]
Not to hide the columns, but the rows. e.g. filter out all rows (wallets+agents+interop profiles), such that I only see wallets. It will become less long vertically. We can also opt that for e.g. interop profiles, many columns are not relevant, and dynamically remove them when the user filters on them. Would require some implementation work though.

**Comment by cre8** [comment]
Ah, got it. Right now it's possible to filter for the wallet type (edge or cloud).

How do we separate wallets from agents? For some people in the SSI space, it's the same. For others a wallet is only the storage component and the agent the implemented logic to handle it.

Is it better to separate like "capable to handle natural persons/natural persons". So if a wallet/agent has none of those, it it for example only capable for iot devices? I think we need more clarification here about the purpose of each filter.

**Comment by samuelmr** [comment]
- only show wallets: `holderCapability = true`
- only show agents: `issuerCapability = true OR verifierCapability = true`
- only show EBSI-compliant wallets: `ebsi = true`
- only show edge (smartphone) wallets: `urlAppStore != '' OR urlGooglePlayStore != ''`
- only show organisational wallets: `organisationalWallet = true`

I'm referring to the characteristics in the main branch's `flattened_wallets.json", but I think you could build the same filters in the `next` version.

**Comment by cre8** [comment]
Right now people can filter on the fields, we do not have any pre defined filters. However each filter config can be shared as a link to share it.
