### ISSUE TITLE
Randomise overview at start

### ISSUE THREAD

**Issue by maaikevanleuken** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#40]
Randomise the shown wallets at starting of website, such that each wallet/agent is shown equally frequent.

**Comment by cre8** [comment]
We had this discussion 4 weeks ago and came to the conclusion, that it has not a big impact. Most lists are sorted by their first column.

It could make things complex when you need to define when the list should be randomized and also not to confuse the user

**Comment by samuelmr** [comment]
Yes, the SIG discussion concluded that the default ordering should be alphabetical. Alphabetical ordering is natural and it helps users find the wallet they are looking for. Random order by default would only confuse everyone.

We could add a feature for a user to randomize the order. It would be easy to implement but would it really be used by someone?

**Comment by maaikevanleuken** [comment]
Ok, agreed. I will update the readme accordingly.

**Comment by maaikevanleuken** [comment]
Ok, agreed. I will update the readme accordingly.

**Comment by cre8** [comment]
@samuelmr I do not think it's worth to implement since there is no real use case for it
