### ISSUE TITLE
Linking to the credential profile comparison group

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#6]
We should use the resources from the https://github.com/openwallet-foundation/credential-format-comparison-sig to point to the existing resources. This would also allow to link back from the comparison group to wallets/agents practically supporting the credential profile or a resource like a key management approach.

The wallet entries have to reference the resource like a did:web entry points to: https://github.com/openwallet-foundation/credential-format-comparison-sig/blob/main/data/Key-Management/did.web.json

# There are two options to implement it:
## the wallet entries include the link of an existing entry
pro: we make sure there is a link to point to, no guessing

contra:
it's more complicated since you need to know that there is a resource in another project. Since the vendors submit their wallet via a PR it's not a custom form field where we can force them to choose one of the existing elements.

## Link guessing
We try to fetch the resource from the github like "is https://github.com/openwallet-foundation/credential-format-comparison-sig/blob/main/data/Key-Management/did.web.json reachable". if so, we can print a hyperlink. If not we just print text.

contra:
in case the user writes did:Web we will not be able to fetch the resource.
someone has to double check for the format.

**Comment by samuelmr** [comment]
I think we can close this issue. @cre8 do you agree?

**Comment by cre8** [comment]
yes
