### ISSUE TITLE
Bug: Add missing fields to generation form

### ISSUE THREAD

**Issue by cre8** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#65]
Challenge creating form based on comments of #37

**Comment by cre8** [comment]
The status management field has a wrong reference, see
![image](https://github.com/openwallet-foundation/digital-wallet-and-agent-overviews-sig/assets/4020915/5d86528b-1dfd-46b2-8191-b2d9d2d7daab)

**Comment by samuelmr** [comment]
I believe I handled the comments of #37 in #71.

The status management issue still remains...

**Comment by cre8** [comment]
@samuelmr I will look at this today
