### ISSUE TITLE
Example links are broken

### ISSUE THREAD

**Issue by samuelmr** [openwallet-foundation/digital-wallet-and-agent-overviews-sig#88]
Example links (with filters) in the Info text no longer work.

**Comment by samuelmr** [comment]
Maybe need to replace /# with /#/#?

**Comment by cre8** [comment]
yes, they need to be fixed. I changed the routing because when using github pages, you can not define rewrite rules so directly calling `https://openwallet-foundation.github.io/digital-wallet-and-agent-overviews-sig/AceID%20Wallet`  will produce a 404. I will make a quick fix for the filters.
